In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Monthly_new.csv")

In [3]:
df = data[:7]

In [4]:
df.columns

Index(['CustomerID', 'Churn', 'BaseCharges', 'TotalCharges', 'DOE',
       'ElectronicBilling', 'ContractType', 'PaymentMethod', 'Retired',
       'HasPartner', 'HasDependents', 'Education', 'Gender',
       'DeviceProtection', 'HasPhoneService', 'InternetServiceCategory',
       'MultipleLines', 'OnlineBackup', 'OnlineSecurity', 'StreamingMovies',
       'StreamingTelevision', 'TechnicalSupport', 'Monthlycharges'],
      dtype='object')

In [5]:
df = df[[ 'Churn', 'BaseCharges', 'TotalCharges', 'DOE',
       'ElectronicBilling', 'PaymentMethod', 'Retired',
       'HasPartner', 'HasDependents', 'Education', 'Gender']]

In [6]:
df

Churn  BaseCharges  TotalCharges        DOE ElectronicBilling  \
0   Yes       372.00       1498.50   7-Sep-11               Yes   
1    No       100.50       5438.50   1-May-07               Yes   
2    No       399.25      10005.00  15-Jan-10               Yes   
3    No       245.00        245.00   6-Dec-11                No   
4    No       320.25       3669.75   9-Feb-11                No   
5    No       498.25      23151.00  26-Mar-08                No   
6   Yes       510.00       5726.75   9-Feb-11               Yes   

               PaymentMethod  Retired  HasPartner  HasDependents  \
0           Electronic check        0           2              2   
1  Bank transfer (automatic)        0           1              1   
2    Credit card (automatic)        0           2              2   
3    Credit card (automatic)        0           2              2   
4  Bank transfer (automatic)        0           2              2   
5               Mailed check        0           1              1   
6           Electronic check        0           1              2   

                  Education  Gender  
0                   Masters    Male  
1                Graduation  Female  
2                Graduation    Male  
3                   Masters    Male  
4  ProfessionalQalification  Female  
5                Graduation  Female  
6       Highschool or below  Female

In [7]:
df.T

0                          1  \
Churn                           Yes                         No   
BaseCharges                   372.0                      100.5   
TotalCharges                 1498.5                     5438.5   
DOE                        7-Sep-11                   1-May-07   
ElectronicBilling               Yes                        Yes   
PaymentMethod      Electronic check  Bank transfer (automatic)   
Retired                           0                          0   
HasPartner                        2                          1   
HasDependents                     2                          1   
Education                   Masters                 Graduation   
Gender                         Male                     Female   

                                         2                        3  \
Churn                                   No                       No   
BaseCharges                         399.25                    245.0   
TotalCharges                       10005.0                    245.0   
DOE                              15-Jan-10                 6-Dec-11   
ElectronicBilling                      Yes                       No   
PaymentMethod      Credit card (automatic)  Credit card (automatic)   
Retired                                  0                        0   
HasPartner                               2                        2   
HasDependents                            2                        2   
Education                       Graduation                  Masters   
Gender                                Male                     Male   

                                           4             5  \
Churn                                     No            No   
BaseCharges                           320.25        498.25   
TotalCharges                         3669.75       23151.0   
DOE                                 9-Feb-11     26-Mar-08   
ElectronicBilling                         No            No   
PaymentMethod      Bank transfer (automatic)  Mailed check   
Retired                                    0             0   
HasPartner                                 2             1   
HasDependents                              2             1   
Education           ProfessionalQalification    Graduation   
Gender                                Female        Female   

                                     6  
Churn                              Yes  
BaseCharges                      510.0  
TotalCharges                   5726.75  
DOE                           9-Feb-11  
ElectronicBilling                  Yes  
PaymentMethod         Electronic check  
Retired                              0  
HasPartner                           1  
HasDependents                        2  
Education          Highschool or below  
Gender                          Female

In [8]:
df1 = df[[ 'Churn', 'BaseCharges', 'TotalCharges','Gender']]
df1

Churn  BaseCharges  TotalCharges  Gender
0   Yes       372.00       1498.50    Male
1    No       100.50       5438.50  Female
2    No       399.25      10005.00    Male
3    No       245.00        245.00    Male
4    No       320.25       3669.75  Female
5    No       498.25      23151.00  Female
6   Yes       510.00       5726.75  Female

In [9]:
df1.groupby("Gender").agg(['max', 'min'])

Churn     BaseCharges        TotalCharges         
         max min         max    min          max      min
Gender                                                   
Female   Yes  No      510.00  100.5      23151.0  3669.75
Male     Yes  No      399.25  245.0      10005.0   245.00

In [10]:
x = pd.Series(['ID12','ID1','ID6','ID12','ID1','ID6','ID12','ID1','ID16'])
y =pd.Series(['2012-06','2012-06','2012-06','2012-07','2012-07','2012-07','2012-08','2012-08','2012-08'])
z = pd.Series([566,10239,524,2360,13858,2352,3950,14738,4104])

In [11]:
frame = {'X': x, "Y" : y, 'Z': z}
dff = pd.DataFrame(frame)

In [12]:
dff

X        Y      Z
0  ID12  2012-06    566
1   ID1  2012-06  10239
2   ID6  2012-06    524
3  ID12  2012-07   2360
4   ID1  2012-07  13858
5   ID6  2012-07   2352
6  ID12  2012-08   3950
7   ID1  2012-08  14738
8  ID16  2012-08   4104

In [13]:
r= dff.pivot(index ='X', columns = 'Y',values ='Z')
r

Y     2012-06  2012-07  2012-08
X                              
ID1   10239.0  13858.0  14738.0
ID12    566.0   2360.0   3950.0
ID16      NaN      NaN   4104.0
ID6     524.0   2352.0      NaN

In [14]:
#r.melt()

Indices of n maximum values in a numpy array

In [15]:
arr = np.array([6,7,8,9,11])
print(arr)
print(arr.argsort()[-3:][::-1])

[ 6  7  8  9 11]
[4 3 2]


In [16]:
arr.argsort()[-3:][::-1]

array([4, 3, 2], dtype=int64)

Getting the items of series A not present in series B

In [17]:
p1 = pd.Series([2,4,6,8,10])
p2 = pd.Series([8,10,12,14,16])
p1[~p1.isin(p2)]

0    2
1    4
2    6
dtype: int64

In [18]:
p1[p1.isin(p2)]

3     8
4    10
dtype: int64

In [19]:
#also we can convert into set and use difference operations
set(p1)-set(p2)

{2, 4, 6}

Getting the items not common to both series A and series B

In [21]:
p_u = pd.Series(np.union1d(p1,p2))
p_i = pd.Series(np.intersect1d(p1,p2))
print("Using Set", set(p_u)-set(p_i))  # set(p_u).difference(set(p_i))


print("\nFrom Series:  \n", p_u[~p_u.isin(p_i)])

Using Set {2, 4, 6, 12, 14, 16}

From Series:  
 0     2
1     4
2     6
5    12
6    14
7    16
dtype: int64


Converting a series to dataframe

In [22]:
s = pd.Series(["a","b","c"], name = "vals")
s.to_frame()

vals
0    a
1    b
2    c

In [23]:
pd.DataFrame(s)

vals
0    a
1    b
2    c

Converting strings to date

In [24]:
from datetime import datetime

In [25]:
str1 = 'Wednesday, July 26, 2021'
str2 = '26/7/21'
str3 = '26-07-2021'

#defining datetimes as objects.
dt1 = datetime.strptime(str1,'%A, %B %d, %Y')
dt2 = datetime.strptime(str2, '%M/%d/%y')
dt3 = datetime.strptime(str3, '%M-%d-%Y')

In [26]:
dt3

datetime.datetime(2021, 1, 7, 0, 26)

Replacing missing values in pandas dataframe.

In [27]:
r

Y     2012-06  2012-07  2012-08
X                              
ID1   10239.0  13858.0  14738.0
ID12    566.0   2360.0   3950.0
ID16      NaN      NaN   4104.0
ID6     524.0   2352.0      NaN

In [28]:
r.apply(lambda x: x.fillna(x.mean()), axis =1)

Y     2012-06  2012-07  2012-08
X                              
ID1   10239.0  13858.0  14738.0
ID12    566.0   2360.0   3950.0
ID16   4104.0   4104.0   4104.0
ID6     524.0   2352.0   1438.0

###### Concat function

In [29]:
s1 = pd.Series([1,2], index=['A','B'], name = 's1')
s2 = pd.Series([3,4], index = ['A', 'B'], name = 's2')

pd.concat([s1,s2], axis =1)

s1  s2
A   1   3
B   2   4

In [30]:
pd.concat([s1,s2], axis =1).reset_index()

index  s1  s2
0     A   1   3
1     B   2   4